### ISSUE TITLE
Array of username and password values in database

### ISSUE THREAD

**Issue by MichaelBujard** [MichaelBujard/DineRush#1]
I need help to create an array of username and password values in the database for isunique() method.

This is so I can loop through the array and check if textfield input is unique. If so, allow registration. If not, don't allow the existing user data to change.

This is what gotusers does. It makes an array, but doesn't update it if I register a new user in real time.

**Comment by rayanazzam** [comment]
Hi Michael, you do not actually need to store anything in an array. To check if an input already exists in the database, all you got to do is point to a reference in the database you want to check, and do child.exists(). This method returns a boolean, and if an entry exists, you can prompt users to pick a different username. I am not quite sure about the syntax, but that is the right idea. You can look it up through the firebase web documentation and tutorials online. Keep playing with it along those lines and if you are unable to implement it by tomorrow, we will work on it in the meeting together. See you then.

**Comment by rayanazzam** [comment]
You can add use this code sinppet in your code:
`var ref = firebase.database().ref("users");
ref.once("value")
  .then(function(snapshot) {
    var a = snapshot.child("theUsernameYouWantToCheck").exists();  // a is now either true or false
    if(a == true) {
          alert("Username is alread taken. Please try again")
   }
   else {
        // You can safely push your user here
    }
  });`

**Comment by MichaelBujard** [comment]
Thanks a mil!
